<?php

namespace App\Models;

use App\Enums\VehicleStatus;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Vehicle extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'registration_number',
        'name',
        'model',
        'type',
        'max_load_capacity_kg',
        'odometer_km',
        'acquisition_cost',
        'status',
        'region',
    ];

    protected function casts(): array
    {
        return [
            'status' => VehicleStatus::class,
            'max_load_capacity_kg' => 'decimal:2',
            'odometer_km' => 'decimal:2',
            'acquisition_cost' => 'decimal:2',
        ];
    }

    // ── Relationships ──

    public function trips(): HasMany
    {
        return $this->hasMany(Trip::class);
    }

    public function maintenanceLogs(): HasMany
    {
        return $this->hasMany(MaintenanceLog::class);
    }

    public function fuelLogs(): HasMany
    {
        return $this->hasMany(FuelLog::class);
    }

    public function expenses(): HasMany
    {
        return $this->hasMany(Expense::class);
    }

    public function documents(): HasMany
    {
        return $this->hasMany(VehicleDocument::class);
    }

    // ── Scopes ──

    public function scopeAvailable($query)
    {
        return $query->where('status', VehicleStatus::Available);
    }

    public function scopeDispatchable($query)
    {
        return $query->whereIn('status', [VehicleStatus::Available]);
    }

    // ── Computed Attributes ──

    /**
     * Get total operational cost for this vehicle.
     */
    public function getOperationalCostAttribute(): float
    {
        $fuelCost = $this->fuelLogs()->sum('total_cost');
        $expenseCost = $this->expenses()->sum('amount');
        $maintenanceCost = $this->maintenanceLogs()->sum('cost');

        return (float) ($fuelCost + $expenseCost + $maintenanceCost);
    }

    /**
     * Get total revenue generated by this vehicle.
     */
    public function getTotalRevenueAttribute(): float
    {
        return (float) $this->trips()->where('status', 'Completed')->sum('revenue');
    }
}
